name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - run: |
        python -m pip install --upgrade pip
        pip install buildozer
    - run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses6 libncursesw6 libffi-dev libssl-dev
        pip install --user --upgrade cython==0.29.36
    - uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
    - run: |
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
    - run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license
    - run: |
        yes | ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager "build-tools;36.0.0" "platforms;android-36" "system-images;android-36;google_apis_playstore_ps16k;arm64-v8a"
    - run: |
        buildozer -v android debug
      working-directory: .
    - uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
