name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Install Buildozer dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip install --user --upgrade cython virtualenv

    - name: Set Java path
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        sudo update-java-alternatives --set ${JAVA_HOME}
        export PATH=$JAVA_HOME/bin:$PATH

    - name: Accept Android SDK License
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

    - name: Install Android SDK Build-Tools
      run: |
        yes | ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager "build-tools;36.0.0"

    - name: Build APK
      run: |
        buildozer -v android debug
      working-directory: .

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
